<?xml version="1.0" encoding="UTF-8"?><testrun name="CalcTest" project="calc" tests="5" started="5" failures="0" errors="1" ignored="0">
  <testsuite name="calculator.calc.CalcTest" time="0.034">
    <testcase name="testDiv" classname="calculator.calc.CalcTest" time="0.027">
      <error>java.lang.ArithmeticException: / by zero&#13;
	at calculator.calc.Calculator.processDiv(Calculator.java:117)&#13;
	at calculator.calc.Calculator.calculate(Calculator.java:40)&#13;
	at calculator.calc.CalcTest.testDiv(CalcTest.java:42)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.java:99)&#13;
	at org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java:81)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)&#13;
	at org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)&#13;
	at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)&#13;
	at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:71)&#13;
	at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:35)&#13;
	at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)&#13;
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testMult" classname="calculator.calc.CalcTest" time="0.003"/>
    <testcase name="testSub" classname="calculator.calc.CalcTest" time="0.001"/>
    <testcase name="testLet" classname="calculator.calc.CalcTest" time="0.001"/>
    <testcase name="testAdd" classname="calculator.calc.CalcTest" time="0.001"/>
  </testsuite>
</testrun>
